spring.application.name=farmyukti

# --- Database Configuration ---
# Ensure you have created a database named 'FarmYukti' in PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/farmyukti
spring.datasource.username=postgres
spring.datasource.password=ROOT
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate / JPA Settings ---
# This automatically updates your tables if you change Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- JSON Handling ---
spring.jackson.serialization.fail-on-empty-beans=false



cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:	
mediaflows_68ed705e-435d-4df9-9b5}
cloudinary.api-key=${CLOUDINARY_API_KEY:699313788799991}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:f8nhrHO9AOgYsizt0RwVy3lb8mvg}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000